import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Award, Trophy } from "lucide-react";

import { TournamentsSection } from "./_components/tournaments-section";
import { SafeguardingPolicies } from "./_components/safeguarding-policies";

const principles = [
  { number: "01", title: "Our mission", icon: Trophy, text: "To build  friendship, teamwork, sportsmanship, 21st century skills and wellness flourish through the power of sports." },
] as const;
export default function HomePage() {
  return <>
    <section className="relative isolate min-h-[720px] overflow-hidden bg-sky-950 text-white"><Image src="/images/reference-0.jpg" alt="ILBC student athletes gathered together" fill priority sizes="100vw" className="object-cover object-center" /><div className="absolute inset-0 bg-slate-950/55" /><div className="relative mx-auto flex min-h-[720px] max-w-7xl items-center px-5 py-24 lg:px-8"><div className="max-w-4xl"><p className="mb-7 flex items-center gap-3 font-bold text-amber-400 text-sm uppercase tracking-[0.12em] before:h-1 before:w-8 before:bg-amber-400">ILBC school sports</p><h1 className="font-serif text-5xl uppercase leading-[0.94] tracking-tight sm:text-7xl lg:text-[5.4rem]">Empowering <span className="text-amber-400">student-athletes</span><br /> through global excellence</h1><p className="mt-7 max-w-3xl text-base text-white/80 leading-7 sm:text-lg">The ILBC School Sports program unites students from diverse backgrounds through competitive teams, rigorous training, and a culture of respect, teamwork, and global citizenship.</p><div className="mt-9 flex flex-wrap gap-4"><Link href="#tournaments" className="inline-flex h-13 items-center bg-amber-400 px-7 font-black text-sky-950 text-sm uppercase hover:bg-amber-300">Live Scores <ArrowRight className="ml-3 size-4" /></Link><Link href="/fixtures" className="inline-flex h-13 items-center border-2 border-amber-400 px-7 font-black text-amber-400 text-sm uppercase hover:bg-amber-400 hover:text-sky-950">View schedules</Link></div></div></div></section>
    <section id="about" className="bg-slate-50 py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="inline-block bg-amber-400 px-4 py-2 font-black text-sky-950 text-xs uppercase tracking-[0.18em]">About the league</p><div className="mt-7 grid gap-5 lg:grid-cols-[1fr_20rem] lg:items-end"><h2 className="max-w-4xl font-serif text-4xl text-sky-900 uppercase leading-tight sm:text-6xl">Empowering student-athletes through excellence</h2><p className="text-slate-500 leading-7">Building champions in sport and character, on every campus, every season.</p></div><div className="mt-14 max-w-3xl">{principles.map(({ number, title, icon: Icon, text }) => <article key={title} className="relative overflow-hidden border border-slate-100 bg-white p-8 lg:p-10"><span className="absolute top-5 right-6 font-black text-5xl text-slate-100">{number}</span><Icon className="mb-7 size-7 text-amber-500" /><h3 className="font-serif text-2xl text-sky-900 uppercase">{title}</h3><p className="mt-5 text-lg text-slate-600 leading-8">{text}</p></article>)}</div></div></section>
    <TournamentsSection />
    <section id="partners" className="bg-sky-900 py-20 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="font-bold text-amber-400 text-xs uppercase tracking-[0.18em]">History & laurels</p><h2 className="mt-4 font-serif text-4xl uppercase sm:text-5xl">Play with purpose.<br />Lead with pride.</h2></div><div className="flex items-center gap-5"><Award className="size-14 text-amber-400" /><p className="max-w-md text-white/70 leading-7">A shared sporting tradition that challenges every student to compete courageously and represent their community well.</p></div></div></section>
    <SafeguardingPolicies />
  </>;
}
